#!/bin/bash

TEEMUXROOT="$( cd -- "$(dirname "$0")" || exit 1 >/dev/null 2>&1 ; pwd -P )"
read -rd '' RUN << EOF
gdb -ex='set confirm off' \
	-ex='set pagination off' \
	-ex='set disassembly-flavor intel' \
	-ex=run \
	-ex=bt \
	-ex=quit \
	--args chillerbot-ux $*
EOF

# :justatest:
cd "$TEEMUXROOT" || exit 1
cd || exit 1

tmux new -s teemux -d
tmux send-keys -t teemux "cd $TEEMUXROOT/client0" C-m
tmux send-keys -t teemux "$RUN" C-m
tmux send-keys -t teemux C-m
tmux split-window -h -t teemux
tmux send-keys -t teemux "cd $TEEMUXROOT/client1" C-m
tmux send-keys -t teemux "$RUN" C-m
tmux send-keys -t teemux C-m
tmux select-window -t teemux:0
tmux attach -t teemux

