#!/bin/bash

TEEMUXROOT="$( cd -- "$(dirname "$0")" || exit 1 >/dev/null 2>&1 ; pwd -P )"
RUN='gdb -ex=run chillerbot-ux'

# :justatest:
cd "$TEEMUXROOT" || exit 1
cd || exit 1

tmux new -s teemux -d
tmux send-keys -t teemux "cd $TEEMUXROOT/client0" C-m
tmux send-keys -t teemux "$RUN" C-m
tmux split-window -h -t teemux
tmux send-keys -t teemux "cd $TEEMUXROOT/client1" C-m
tmux send-keys -t teemux "$RUN" C-m
tmux select-window -t teemux:0
tmux attach -t teemux

